# Generated by Django 3.2.5 on 2022-04-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_alter_admin_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='availability',
            field=models.CharField(default='Yes', max_length=100),
        ),
    ]
